# Generated by Django 5.0.6 on 2024-07-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='datetime_created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='datetime_modified',
        ),
    ]
