# Generated by Django 5.0.6 on 2024-07-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_datetime_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='datetime_modified',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
