# Generated by Django 5.0.6 on 2024-07-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='cover',
            field=models.ImageField(blank=True, upload_to='product/product_cover/', verbose_name='product image'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
