# Generated by Django 5.0.6 on 2024-08-03 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_discount_percent_product_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
