# Generated by Django 5.0.6 on 2024-08-03 14:59

import products.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=products.models.IntegerRangeField(blank=True, default=0),
        ),
    ]
